# Server Properties
server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: true
        http-only: true

# Spring Properties
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  session:
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always

  datasource:
    url: jdbc:mysql://localhost:3306/httpsspringsecurity?serverTimezone=UTC
    username: root
    password: bcmc1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    livereload:
      enabled: true
